package com.scooterre.client.protocol

/**
 * Experimental, READ-ONLY property tables for the models whose MIoT spec Xiaomi publishes (Elite, 5 Plus, 6, 6 Lite,
 * 6 Essential, 6 Pro, 6 Ultra; services 2-5: work state, battery, control, options). Generated from the public specs
 * on miot-spec.org - never verified against a real device. Values are shown as the scooter sends them: nothing is
 * scaled or converted, because the scaling of the floats is not known. All names carry the prefix A_ so none of the
 * 5-series scalings and labels is applied to them; only four names are shared with the 5-series
 * table so the overview works: BATTERY_LEVEL, RIDING_MODE (1 = Walk, 2 = Drive, 3 = Sport), IS_LOCKED and
 * TAIL_LIGHT_IS_ON. Left out on purpose and never read: pairing secret (oob), reset actions, bind/unbind, passwords,
 * anti-activation and the debug/after-sales services.
 */
object FamilyAProfiles {
    private fun p(siid: Int, piid: Int, name: String, type: SpecType) = SpecProperty(siid, piid, name, type)

    private fun profile(
        all: List<SpecProperty>, ride: List<String>, battery: List<String>, settings: List<String>,
        vehicle: List<String>, ident: List<String>,
    ) = SpecProfile(
        all = all, settable = emptySet(), writeOnly = emptySet(), cycleProperties = emptySet(),
        regionSensitiveProperties = emptySet(), tabRide = ride, tabBattery = battery, tabSettings = settings,
        tabVehicleStatus = vehicle, tabIdentification = ident, tabRideLog = emptyList(), readOnly = true,
    )

    // xiaomi.scooter.elite
    val ELITE = profile(
        listOf(
            p(2, 1, "A_TEMP", SpecType.UINT8),
            p(2, 2, "A_MILEAGE_TOTAL", SpecType.FLOAT),
            p(2, 4, "RIDING_MODE", SpecType.UINT8),
            p(2, 5, "A_MILEAGE_LEFT", SpecType.FLOAT),
            p(2, 6, "A_MILEAGE", SpecType.FLOAT),
            p(2, 7, "A_FAULT_CODES", SpecType.UINT32),
            p(2, 8, "A_RIDING_RECORDS", SpecType.STRING),
            p(2, 9, "A_RIDING_ACTIVE", SpecType.BOOL),
            p(3, 1, "BATTERY_LEVEL", SpecType.UINT8),
            p(3, 2, "A_CHARGE_STATE", SpecType.UINT8),
            p(3, 3, "A_VOLTAGE", SpecType.FLOAT),
            p(3, 4, "A_ELECTRICITY", SpecType.FLOAT),
            p(3, 5, "A_BATTERY_HEALTH", SpecType.UINT8),
            p(3, 6, "A_BATTERY_TEMP", SpecType.UINT8),
            p(3, 7, "A_BATTERY_POWER", SpecType.FLOAT),
            p(3, 8, "A_BATTERY_SN", SpecType.STRING),
            p(3, 9, "A_BATTERY_DATE", SpecType.STRING),
            p(3, 10, "A_BP_RESET_CAPACITY", SpecType.UINT16),
            p(3, 11, "A_BP_DIS_CAPACITY", SpecType.UINT16),
            p(3, 12, "A_BP_DIS_POWER", SpecType.UINT32),
            p(3, 13, "A_BP_CYCLE_TIMES", SpecType.UINT16),
            p(3, 14, "A_BP_OVER_DIS_TIMES", SpecType.UINT16),
            p(3, 15, "A_BP_CHARGE_SECONDS", SpecType.UINT32),
            p(3, 16, "A_BP_STORE_SECONDS", SpecType.UINT32),
            p(3, 17, "A_BP_BMS_VERSION", SpecType.STRING),
            p(4, 1, "IS_LOCKED", SpecType.BOOL),
            p(4, 2, "A_ENERGY_LEVEL", SpecType.UINT8),
            p(4, 3, "A_ACTIVE", SpecType.BOOL),
            p(4, 4, "TAIL_LIGHT_IS_ON", SpecType.BOOL),
            p(4, 5, "A_FIRST_ACTIVE_TIME", SpecType.UINT32),
            p(4, 6, "A_SERVER_TIME", SpecType.UINT32),
            p(5, 1, "A_MILEAGE_UNIT", SpecType.UINT8),
            p(5, 2, "A_PRESSURE_SWITCH", SpecType.BOOL),
            p(5, 3, "A_PRESSURE_PERIOD", SpecType.UINT8),
            p(5, 4, "A_PRESSURE_START_TIME", SpecType.UINT32),
            p(5, 5, "A_PRESSURE_ALARM", SpecType.BOOL),
            p(5, 6, "A_PRESSURE_REST_DAYS", SpecType.UINT8),
        ),
        ride = listOf("A_TEMP", "A_MILEAGE_TOTAL", "A_MILEAGE_LEFT", "A_MILEAGE", "A_RIDING_RECORDS", "A_RIDING_ACTIVE"),
        battery = listOf("BATTERY_LEVEL", "A_CHARGE_STATE", "A_VOLTAGE", "A_ELECTRICITY", "A_BATTERY_HEALTH", "A_BATTERY_TEMP", "A_BATTERY_POWER", "A_BP_RESET_CAPACITY", "A_BP_DIS_CAPACITY", "A_BP_DIS_POWER", "A_BP_CYCLE_TIMES", "A_BP_OVER_DIS_TIMES", "A_BP_CHARGE_SECONDS", "A_BP_STORE_SECONDS"),
        settings = listOf("RIDING_MODE", "IS_LOCKED", "A_ENERGY_LEVEL", "A_ACTIVE", "TAIL_LIGHT_IS_ON", "A_SERVER_TIME"),
        vehicle = listOf("A_FAULT_CODES", "A_MILEAGE_UNIT", "A_PRESSURE_SWITCH", "A_PRESSURE_PERIOD", "A_PRESSURE_START_TIME", "A_PRESSURE_ALARM", "A_PRESSURE_REST_DAYS"),
        ident = listOf("A_BATTERY_SN", "A_BATTERY_DATE", "A_BP_BMS_VERSION", "A_FIRST_ACTIVE_TIME"),
    )

    // xiaomi.scooter.5plus
    val PLUS_5 = profile(
        listOf(
            p(2, 1, "A_MOTOR_TEMP", SpecType.UINT8),
            p(2, 2, "A_MILEAGE_TOTAL", SpecType.FLOAT),
            p(2, 4, "RIDING_MODE", SpecType.UINT8),
            p(2, 5, "A_MILEAGE_LEFT", SpecType.FLOAT),
            p(2, 6, "A_MILEAGE", SpecType.FLOAT),
            p(2, 7, "A_FAULT_CODES", SpecType.UINT32),
            p(2, 8, "A_RIDING_RECORDS", SpecType.STRING),
            p(2, 9, "A_RIDING_ACTIVE", SpecType.BOOL),
            p(2, 10, "A_LOW_POWER_ACTIVE", SpecType.BOOL),
            p(3, 1, "BATTERY_LEVEL", SpecType.UINT8),
            p(3, 2, "A_CHARGE_STATE", SpecType.UINT8),
            p(3, 3, "A_VOLTAGE", SpecType.FLOAT),
            p(3, 4, "A_ELECTRICITY", SpecType.FLOAT),
            p(3, 5, "A_BATTERY_HEALTH", SpecType.UINT8),
            p(3, 6, "A_BATTERY_TEMP", SpecType.UINT8),
            p(3, 7, "A_BATTERY_POWER", SpecType.FLOAT),
            p(3, 8, "A_BATTERY_SN", SpecType.STRING),
            p(3, 9, "A_BATTERY_DATE", SpecType.STRING),
            p(3, 10, "A_BP_RESET_CAPACITY", SpecType.UINT16),
            p(3, 11, "A_BP_DIS_CAPACITY", SpecType.UINT16),
            p(3, 12, "A_BP_DIS_POWER", SpecType.UINT32),
            p(3, 13, "A_BP_CYCLE_TIMES", SpecType.UINT16),
            p(3, 14, "A_BP_OVER_DIS_TIMES", SpecType.UINT16),
            p(3, 15, "A_BP_CHARGE_SECONDS", SpecType.UINT32),
            p(3, 16, "A_BP_STORE_SECONDS", SpecType.UINT32),
            p(3, 17, "A_BP_BMS_VERSION", SpecType.STRING),
            p(4, 1, "IS_LOCKED", SpecType.BOOL),
            p(4, 2, "A_ENERGY_LEVEL", SpecType.UINT8),
            p(4, 3, "A_ACTIVE", SpecType.BOOL),
            p(4, 4, "TAIL_LIGHT_IS_ON", SpecType.BOOL),
            p(4, 5, "A_FIRST_ACTIVE_TIME", SpecType.UINT32),
            p(4, 6, "A_SERVER_TIME", SpecType.UINT32),
            p(4, 7, "A_TCS_SWITCH", SpecType.BOOL),
            p(4, 8, "A_HEADLIGHT_SWITCH", SpecType.BOOL),
            p(4, 9, "A_DEVICE_FOUND_SWITCH", SpecType.BOOL),
            p(5, 1, "A_MILEAGE_UNIT", SpecType.UINT8),
            p(5, 2, "A_PRESSURE_SWITCH", SpecType.BOOL),
            p(5, 3, "A_PRESSURE_PERIOD", SpecType.UINT8),
            p(5, 4, "A_PRESSURE_START_TIME", SpecType.UINT32),
            p(5, 5, "A_PRESSURE_ALARM", SpecType.BOOL),
            p(5, 6, "A_PRESSURE_REST_DAYS", SpecType.UINT8),
            p(5, 7, "A_START_SPEED", SpecType.UINT8),
        ),
        ride = listOf("A_MOTOR_TEMP", "A_MILEAGE_TOTAL", "A_MILEAGE_LEFT", "A_MILEAGE", "A_RIDING_RECORDS", "A_RIDING_ACTIVE", "A_LOW_POWER_ACTIVE"),
        battery = listOf("BATTERY_LEVEL", "A_CHARGE_STATE", "A_VOLTAGE", "A_ELECTRICITY", "A_BATTERY_HEALTH", "A_BATTERY_TEMP", "A_BATTERY_POWER", "A_BP_RESET_CAPACITY", "A_BP_DIS_CAPACITY", "A_BP_DIS_POWER", "A_BP_CYCLE_TIMES", "A_BP_OVER_DIS_TIMES", "A_BP_CHARGE_SECONDS", "A_BP_STORE_SECONDS"),
        settings = listOf("RIDING_MODE", "IS_LOCKED", "A_ENERGY_LEVEL", "A_ACTIVE", "TAIL_LIGHT_IS_ON", "A_SERVER_TIME", "A_TCS_SWITCH", "A_HEADLIGHT_SWITCH", "A_DEVICE_FOUND_SWITCH"),
        vehicle = listOf("A_FAULT_CODES", "A_MILEAGE_UNIT", "A_PRESSURE_SWITCH", "A_PRESSURE_PERIOD", "A_PRESSURE_START_TIME", "A_PRESSURE_ALARM", "A_PRESSURE_REST_DAYS", "A_START_SPEED"),
        ident = listOf("A_BATTERY_SN", "A_BATTERY_DATE", "A_BP_BMS_VERSION", "A_FIRST_ACTIVE_TIME"),
    )

    // xiaomi.scooter.6
    val SIX = profile(
        listOf(
            p(2, 1, "A_MOTOR_TEMP", SpecType.UINT8),
            p(2, 2, "A_MILEAGE_TOTAL", SpecType.FLOAT),
            p(2, 4, "RIDING_MODE", SpecType.UINT8),
            p(2, 5, "A_MILEAGE_LEFT", SpecType.FLOAT),
            p(2, 6, "A_FAULT_CODES", SpecType.UINT32),
            p(2, 7, "A_RIDING_RECORDS", SpecType.STRING),
            p(2, 8, "A_RIDING_ACTIVE", SpecType.BOOL),
            p(3, 1, "BATTERY_LEVEL", SpecType.UINT8),
            p(3, 2, "A_CHARGE_STATE", SpecType.UINT8),
            p(3, 3, "A_VOLTAGE", SpecType.FLOAT),
            p(3, 4, "A_ELECTRICITY", SpecType.FLOAT),
            p(3, 5, "A_BATTERY_HEALTH", SpecType.UINT8),
            p(3, 6, "A_BATTERY_TEMP", SpecType.UINT8),
            p(3, 7, "A_BATTERY_POWER", SpecType.FLOAT),
            p(3, 8, "A_BATTERY_SN", SpecType.STRING),
            p(3, 9, "A_BATTERY_DATE", SpecType.STRING),
            p(3, 10, "A_BP_RESET_CAPACITY", SpecType.UINT16),
            p(3, 11, "A_BP_DIS_CAPACITY", SpecType.UINT16),
            p(3, 12, "A_BP_DIS_POWER", SpecType.UINT32),
            p(3, 13, "A_BP_CYCLE_TIMES", SpecType.UINT16),
            p(3, 14, "A_BP_OVER_DIS_TIMES", SpecType.UINT16),
            p(3, 15, "A_BP_CHARGE_SECONDS", SpecType.UINT32),
            p(3, 16, "A_BP_STORE_SECONDS", SpecType.UINT32),
            p(3, 17, "A_BP_BMS_VERSION", SpecType.STRING),
            p(4, 1, "IS_LOCKED", SpecType.BOOL),
            p(4, 2, "A_ENERGY_LEVEL", SpecType.UINT8),
            p(4, 3, "A_ACTIVE", SpecType.BOOL),
            p(4, 4, "TAIL_LIGHT_IS_ON", SpecType.BOOL),
            p(4, 5, "A_FIRST_ACTIVE_TIME", SpecType.UINT32),
            p(4, 6, "A_AUTO_OFF_TIMER", SpecType.UINT8),
            p(4, 7, "A_OFF_AUTO_LOCK_SWITCH", SpecType.BOOL),
            p(4, 8, "A_SERVER_TIME", SpecType.UINT32),
            p(5, 1, "A_MILEAGE_UNIT", SpecType.UINT8),
            p(5, 2, "A_PRESSURE_SWITCH", SpecType.BOOL),
            p(5, 3, "A_PRESSURE_PERIOD", SpecType.UINT8),
            p(5, 4, "A_PRESSURE_START_TIME", SpecType.UINT32),
            p(5, 5, "A_PRESSURE_ALARM", SpecType.BOOL),
            p(5, 6, "A_PRESSURE_REST_DAYS", SpecType.UINT8),
            p(5, 7, "A_START_SPEED", SpecType.UINT8),
        ),
        ride = listOf("A_MOTOR_TEMP", "A_MILEAGE_TOTAL", "A_MILEAGE_LEFT", "A_RIDING_RECORDS", "A_RIDING_ACTIVE"),
        battery = listOf("BATTERY_LEVEL", "A_CHARGE_STATE", "A_VOLTAGE", "A_ELECTRICITY", "A_BATTERY_HEALTH", "A_BATTERY_TEMP", "A_BATTERY_POWER", "A_BP_RESET_CAPACITY", "A_BP_DIS_CAPACITY", "A_BP_DIS_POWER", "A_BP_CYCLE_TIMES", "A_BP_OVER_DIS_TIMES", "A_BP_CHARGE_SECONDS", "A_BP_STORE_SECONDS"),
        settings = listOf("RIDING_MODE", "IS_LOCKED", "A_ENERGY_LEVEL", "A_ACTIVE", "TAIL_LIGHT_IS_ON", "A_AUTO_OFF_TIMER", "A_OFF_AUTO_LOCK_SWITCH", "A_SERVER_TIME"),
        vehicle = listOf("A_FAULT_CODES", "A_MILEAGE_UNIT", "A_PRESSURE_SWITCH", "A_PRESSURE_PERIOD", "A_PRESSURE_START_TIME", "A_PRESSURE_ALARM", "A_PRESSURE_REST_DAYS", "A_START_SPEED"),
        ident = listOf("A_BATTERY_SN", "A_BATTERY_DATE", "A_BP_BMS_VERSION", "A_FIRST_ACTIVE_TIME"),
    )

    // xiaomi.scooter.6lite
    val SIX_LITE = profile(
        listOf(
            p(2, 1, "A_MOTOR_TEMP", SpecType.UINT8),
            p(2, 2, "A_MILEAGE_TOTAL", SpecType.FLOAT),
            p(2, 4, "RIDING_MODE", SpecType.UINT8),
            p(2, 5, "A_MILEAGE_LEFT", SpecType.FLOAT),
            p(2, 6, "A_FAULT_CODES", SpecType.UINT32),
            p(2, 7, "A_RIDING_RECORDS", SpecType.STRING),
            p(2, 8, "A_RIDING_ACTIVE", SpecType.BOOL),
            p(3, 1, "BATTERY_LEVEL", SpecType.UINT8),
            p(3, 2, "A_CHARGE_STATE", SpecType.UINT8),
            p(3, 3, "A_VOLTAGE", SpecType.FLOAT),
            p(3, 4, "A_ELECTRICITY", SpecType.FLOAT),
            p(3, 5, "A_BATTERY_HEALTH", SpecType.UINT8),
            p(3, 6, "A_BATTERY_TEMP", SpecType.UINT8),
            p(3, 7, "A_BATTERY_POWER", SpecType.FLOAT),
            p(3, 8, "A_BATTERY_SN", SpecType.STRING),
            p(3, 9, "A_BATTERY_DATE", SpecType.STRING),
            p(3, 10, "A_BP_RESET_CAPACITY", SpecType.UINT16),
            p(3, 11, "A_BP_DIS_CAPACITY", SpecType.UINT16),
            p(3, 12, "A_BP_DIS_POWER", SpecType.UINT32),
            p(3, 13, "A_BP_CYCLE_TIMES", SpecType.UINT16),
            p(3, 14, "A_BP_OVER_DIS_TIMES", SpecType.UINT16),
            p(3, 15, "A_BP_CHARGE_SECONDS", SpecType.UINT32),
            p(3, 16, "A_BP_STORE_SECONDS", SpecType.UINT32),
            p(3, 17, "A_BP_BMS_VERSION", SpecType.STRING),
            p(4, 1, "IS_LOCKED", SpecType.BOOL),
            p(4, 2, "A_ENERGY_LEVEL", SpecType.UINT8),
            p(4, 3, "A_ACTIVE", SpecType.BOOL),
            p(4, 4, "TAIL_LIGHT_IS_ON", SpecType.BOOL),
            p(4, 5, "A_FIRST_ACTIVE_TIME", SpecType.UINT32),
            p(4, 6, "A_AUTO_OFF_TIMER", SpecType.UINT8),
            p(4, 7, "A_OFF_AUTO_LOCK_SWITCH", SpecType.BOOL),
            p(5, 1, "A_MILEAGE_UNIT", SpecType.UINT8),
            p(5, 2, "A_PRESSURE_SWITCH", SpecType.BOOL),
            p(5, 3, "A_PRESSURE_PERIOD", SpecType.UINT8),
            p(5, 4, "A_PRESSURE_START_TIME", SpecType.UINT32),
            p(5, 5, "A_PRESSURE_ALARM", SpecType.UINT8),
        ),
        ride = listOf("A_MOTOR_TEMP", "A_MILEAGE_TOTAL", "A_MILEAGE_LEFT", "A_RIDING_RECORDS", "A_RIDING_ACTIVE"),
        battery = listOf("BATTERY_LEVEL", "A_CHARGE_STATE", "A_VOLTAGE", "A_ELECTRICITY", "A_BATTERY_HEALTH", "A_BATTERY_TEMP", "A_BATTERY_POWER", "A_BP_RESET_CAPACITY", "A_BP_DIS_CAPACITY", "A_BP_DIS_POWER", "A_BP_CYCLE_TIMES", "A_BP_OVER_DIS_TIMES", "A_BP_CHARGE_SECONDS", "A_BP_STORE_SECONDS"),
        settings = listOf("RIDING_MODE", "IS_LOCKED", "A_ENERGY_LEVEL", "A_ACTIVE", "TAIL_LIGHT_IS_ON", "A_AUTO_OFF_TIMER", "A_OFF_AUTO_LOCK_SWITCH"),
        vehicle = listOf("A_FAULT_CODES", "A_MILEAGE_UNIT", "A_PRESSURE_SWITCH", "A_PRESSURE_PERIOD", "A_PRESSURE_START_TIME", "A_PRESSURE_ALARM"),
        ident = listOf("A_BATTERY_SN", "A_BATTERY_DATE", "A_BP_BMS_VERSION", "A_FIRST_ACTIVE_TIME"),
    )

    // xiaomi.scooter.6esstl
    val SIX_ESSTL = profile(
        listOf(
            p(2, 1, "A_MOTOR_TEMP", SpecType.UINT8),
            p(2, 2, "A_MILEAGE_TOTAL", SpecType.FLOAT),
            p(2, 4, "RIDING_MODE", SpecType.UINT8),
            p(2, 5, "A_MILEAGE_LEFT", SpecType.FLOAT),
            p(2, 6, "A_FAULT_CODES", SpecType.UINT32),
            p(2, 7, "A_RIDING_RECORDS", SpecType.STRING),
            p(2, 8, "A_RIDING_ACTIVE", SpecType.BOOL),
            p(3, 1, "BATTERY_LEVEL", SpecType.UINT8),
            p(3, 2, "A_CHARGE_STATE", SpecType.UINT8),
            p(3, 3, "A_VOLTAGE", SpecType.FLOAT),
            p(3, 4, "A_ELECTRICITY", SpecType.FLOAT),
            p(3, 5, "A_BATTERY_HEALTH", SpecType.UINT8),
            p(3, 6, "A_BATTERY_TEMP", SpecType.UINT8),
            p(3, 7, "A_BATTERY_POWER", SpecType.FLOAT),
            p(3, 8, "A_BATTERY_SN", SpecType.STRING),
            p(3, 9, "A_BATTERY_DATE", SpecType.STRING),
            p(3, 10, "A_BP_RESET_CAPACITY", SpecType.UINT16),
            p(3, 11, "A_BP_DIS_CAPACITY", SpecType.UINT16),
            p(3, 12, "A_BP_DIS_POWER", SpecType.UINT32),
            p(3, 13, "A_BP_CYCLE_TIMES", SpecType.UINT16),
            p(3, 14, "A_BP_OVER_DIS_TIMES", SpecType.UINT16),
            p(3, 15, "A_BP_CHARGE_SECONDS", SpecType.UINT32),
            p(3, 16, "A_BP_STORE_SECONDS", SpecType.UINT32),
            p(3, 17, "A_BP_BMS_VERSION", SpecType.STRING),
            p(4, 1, "IS_LOCKED", SpecType.BOOL),
            p(4, 2, "A_ENERGY_LEVEL", SpecType.UINT8),
            p(4, 3, "A_ACTIVE", SpecType.BOOL),
            p(4, 4, "TAIL_LIGHT_IS_ON", SpecType.BOOL),
            p(4, 5, "A_FIRST_ACTIVE_TIME", SpecType.UINT32),
            p(4, 6, "A_AUTO_OFF_TIMER", SpecType.UINT8),
            p(4, 7, "A_OFF_AUTO_LOCK_SWITCH", SpecType.BOOL),
            p(5, 1, "A_MILEAGE_UNIT", SpecType.UINT8),
            p(5, 2, "A_PRESSURE_SWITCH", SpecType.BOOL),
            p(5, 3, "A_PRESSURE_PERIOD", SpecType.UINT8),
            p(5, 4, "A_PRESSURE_START_TIME", SpecType.UINT32),
            p(5, 5, "A_PRESSURE_ALARM", SpecType.UINT8),
            p(5, 6, "A_START_SPEED", SpecType.UINT8),
            p(5, 7, "A_TCS_SWITCH", SpecType.BOOL),
            p(5, 8, "A_GEAR_D_MAX_SPEED", SpecType.UINT8),
        ),
        ride = listOf("A_MOTOR_TEMP", "A_MILEAGE_TOTAL", "A_MILEAGE_LEFT", "A_RIDING_RECORDS", "A_RIDING_ACTIVE"),
        battery = listOf("BATTERY_LEVEL", "A_CHARGE_STATE", "A_VOLTAGE", "A_ELECTRICITY", "A_BATTERY_HEALTH", "A_BATTERY_TEMP", "A_BATTERY_POWER", "A_BP_RESET_CAPACITY", "A_BP_DIS_CAPACITY", "A_BP_DIS_POWER", "A_BP_CYCLE_TIMES", "A_BP_OVER_DIS_TIMES", "A_BP_CHARGE_SECONDS", "A_BP_STORE_SECONDS"),
        settings = listOf("RIDING_MODE", "IS_LOCKED", "A_ENERGY_LEVEL", "A_ACTIVE", "TAIL_LIGHT_IS_ON", "A_AUTO_OFF_TIMER", "A_OFF_AUTO_LOCK_SWITCH"),
        vehicle = listOf("A_FAULT_CODES", "A_MILEAGE_UNIT", "A_PRESSURE_SWITCH", "A_PRESSURE_PERIOD", "A_PRESSURE_START_TIME", "A_PRESSURE_ALARM", "A_START_SPEED", "A_TCS_SWITCH", "A_GEAR_D_MAX_SPEED"),
        ident = listOf("A_BATTERY_SN", "A_BATTERY_DATE", "A_BP_BMS_VERSION", "A_FIRST_ACTIVE_TIME"),
    )

    // xiaomi.scooter.6pro
    val SIX_PRO = profile(
        listOf(
            p(3, 1, "BATTERY_LEVEL", SpecType.UINT8),
            p(3, 2, "A_CHARGING_STATUS", SpecType.UINT8),
            p(3, 3, "A_VOLTAGE", SpecType.FLOAT),
            p(3, 4, "A_ELECTRICITY", SpecType.FLOAT),
            p(3, 5, "A_BATTERY_HEALTH", SpecType.UINT8),
            p(3, 6, "A_BATTERY_TEMP", SpecType.UINT8),
            p(3, 7, "A_BATTERY_POWER", SpecType.FLOAT),
            p(3, 8, "A_BATTERY_SN", SpecType.STRING),
            p(3, 9, "A_BATTERY_DATE", SpecType.STRING),
            p(3, 10, "A_BP_RESET_CAPACITY", SpecType.UINT16),
            p(3, 11, "A_BP_DIS_CAPACITY", SpecType.UINT16),
            p(3, 12, "A_BP_DIS_POWER", SpecType.UINT32),
            p(3, 13, "A_BP_CYCLE_TIMES", SpecType.UINT16),
            p(3, 14, "A_BP_OVER_DIS_TIMES", SpecType.UINT16),
            p(3, 15, "A_BP_CHARGE_SECONDS", SpecType.UINT32),
            p(3, 16, "A_BP_STORE_SECONDS", SpecType.UINT32),
            p(3, 17, "A_BP_BMS_VERSION", SpecType.STRING),
            p(3, 18, "A_BP_SOH", SpecType.UINT8),
            p(3, 19, "A_BP_SELF_DIS", SpecType.UINT8),
            p(3, 20, "A_BP_ENERGY_THROUGHPUT", SpecType.UINT32),
            p(3, 21, "A_BP_CAP_THROUGHPUT", SpecType.UINT16),
            p(3, 22, "A_BP_DEEP_DIS_TIMES", SpecType.UINT16),
            p(4, 1, "A_FIRST_ACTIVE_TIME", SpecType.UINT32),
            p(4, 2, "A_ACTIVE", SpecType.BOOL),
            p(4, 3, "A_ENERGY_RECOVERY", SpecType.UINT8),
            p(4, 4, "TAIL_LIGHT_IS_ON", SpecType.BOOL),
            p(4, 5, "A_BRAKE_LIGHT_LINKAGE", SpecType.UINT8),
            p(4, 6, "IS_LOCKED", SpecType.BOOL),
            p(4, 7, "A_TCS_TRACTION", SpecType.BOOL),
            p(4, 8, "A_ENVIRONMENTAL_LIGHTS", SpecType.BOOL),
            p(4, 9, "A_BLE_FIND_VEHICLE", SpecType.BOOL),
            p(4, 10, "A_BLE_FIND_SWICH", SpecType.BOOL),
            p(4, 11, "A_E_ABS", SpecType.BOOL),
            p(4, 12, "A_STARTING_SPEED", SpecType.UINT8),
            p(4, 13, "A_AUTO_LOCK", SpecType.BOOL),
            p(4, 15, "A_AUTOMATIC_SHUTDOWN", SpecType.UINT8),
            p(4, 17, "A_ABNORMAL_REPORTING", SpecType.UINT32),
            p(4, 18, "A_PHONE_TIME", SpecType.STRING),
            p(4, 21, "A_CHARGING", SpecType.UINT8),
            p(2, 1, "RIDING_MODE", SpecType.UINT8),
            p(2, 2, "A_REMAINING_MILEAGE", SpecType.FLOAT),
            p(2, 3, "A_COMPANION_TIME", SpecType.INT32),
            p(2, 4, "A_TOTAL_DRIVING", SpecType.INT16),
            p(2, 5, "A_MOTOR_TEMPERATURE", SpecType.UINT8),
            p(2, 6, "A_DRIVING_TIME", SpecType.UINT32),
            p(2, 7, "A_DRIVING_MILEAGE", SpecType.INT32),
            p(2, 8, "A_AVERAGE_SPEED", SpecType.INT8),
            p(2, 9, "A_RECENT_MILEAGE", SpecType.STRING),
            p(2, 11, "A_VCU_FIRMWARE_VERSION", SpecType.STRING),
            p(2, 12, "A_VCU_HARDWARE_VERSION", SpecType.STRING),
            p(2, 13, "A_VCU_SN", SpecType.STRING),
            p(2, 14, "A_BMS_FIRMWARE_VERSION", SpecType.STRING),
            p(2, 15, "A_BMS_HARDWARE_VERSION", SpecType.STRING),
            p(2, 16, "A_BMS_SN", SpecType.STRING),
            p(2, 17, "A_ONOFF_STATUS", SpecType.UINT8),
            p(2, 18, "A_SCOOTER_SN", SpecType.STRING),
            p(2, 19, "A_VCU_SPEED", SpecType.UINT32),
            p(2, 20, "A_METER_FW_VERSION", SpecType.STRING),
            p(5, 1, "A_MILEAGE_UNIT", SpecType.UINT8),
            p(5, 2, "A_PRESSURE_SWITCH", SpecType.BOOL),
            p(5, 3, "A_PRESSURE_PERIOD", SpecType.UINT8),
            p(5, 4, "A_PRESSURE_START_TIME", SpecType.UINT32),
            p(5, 5, "A_PRESSURE_REST_DAYS", SpecType.UINT8),
            p(5, 6, "A_SKU", SpecType.STRING),
        ),
        ride = listOf("A_REMAINING_MILEAGE", "A_COMPANION_TIME", "A_TOTAL_DRIVING", "A_MOTOR_TEMPERATURE", "A_DRIVING_TIME", "A_DRIVING_MILEAGE", "A_AVERAGE_SPEED", "A_RECENT_MILEAGE", "A_ONOFF_STATUS", "A_VCU_SPEED"),
        battery = listOf("BATTERY_LEVEL", "A_CHARGING_STATUS", "A_VOLTAGE", "A_ELECTRICITY", "A_BATTERY_HEALTH", "A_BATTERY_TEMP", "A_BATTERY_POWER", "A_BP_RESET_CAPACITY", "A_BP_DIS_CAPACITY", "A_BP_DIS_POWER", "A_BP_CYCLE_TIMES", "A_BP_OVER_DIS_TIMES", "A_BP_CHARGE_SECONDS", "A_BP_STORE_SECONDS", "A_BP_SOH", "A_BP_SELF_DIS", "A_BP_ENERGY_THROUGHPUT", "A_BP_CAP_THROUGHPUT", "A_BP_DEEP_DIS_TIMES"),
        settings = listOf("A_ACTIVE", "A_ENERGY_RECOVERY", "TAIL_LIGHT_IS_ON", "A_BRAKE_LIGHT_LINKAGE", "IS_LOCKED", "A_TCS_TRACTION", "A_ENVIRONMENTAL_LIGHTS", "A_BLE_FIND_VEHICLE", "A_BLE_FIND_SWICH", "A_E_ABS", "A_STARTING_SPEED", "A_AUTO_LOCK", "A_AUTOMATIC_SHUTDOWN", "A_ABNORMAL_REPORTING", "A_PHONE_TIME", "A_CHARGING", "RIDING_MODE"),
        vehicle = listOf("A_MILEAGE_UNIT", "A_PRESSURE_SWITCH", "A_PRESSURE_PERIOD", "A_PRESSURE_START_TIME", "A_PRESSURE_REST_DAYS", "A_SKU"),
        ident = listOf("A_BATTERY_SN", "A_BATTERY_DATE", "A_BP_BMS_VERSION", "A_FIRST_ACTIVE_TIME", "A_VCU_FIRMWARE_VERSION", "A_VCU_HARDWARE_VERSION", "A_VCU_SN", "A_BMS_FIRMWARE_VERSION", "A_BMS_HARDWARE_VERSION", "A_BMS_SN", "A_SCOOTER_SN", "A_METER_FW_VERSION"),
    )

    // xiaomi.scooter.cross
    val SIX_ULTRA = profile(
        listOf(
            p(3, 1, "BATTERY_LEVEL", SpecType.UINT8),
            p(3, 2, "A_CHARGING_STATUS", SpecType.UINT8),
            p(3, 3, "A_VOLTAGE", SpecType.FLOAT),
            p(3, 4, "A_ELECTRICITY", SpecType.FLOAT),
            p(3, 5, "A_BATTERY_HEALTH", SpecType.UINT8),
            p(3, 6, "A_BATTERY_TEMP", SpecType.INT16),
            p(3, 7, "A_BATTERY_POWER", SpecType.FLOAT),
            p(3, 8, "A_BATTERY_SN", SpecType.STRING),
            p(3, 9, "A_BATTERY_DATE", SpecType.STRING),
            p(3, 10, "A_BP_RESET_CAPACITY", SpecType.UINT16),
            p(3, 11, "A_BP_DIS_CAPACITY", SpecType.UINT16),
            p(3, 12, "A_BP_DIS_POWER", SpecType.UINT32),
            p(3, 13, "A_BP_CYCLE_TIMES", SpecType.UINT16),
            p(3, 14, "A_BP_OVER_DIS_TIMES", SpecType.UINT16),
            p(3, 15, "A_BP_CHARGE_SECONDS", SpecType.UINT32),
            p(3, 16, "A_BP_STORE_SECONDS", SpecType.UINT32),
            p(3, 17, "A_SELF_DISCHARGE_RATE", SpecType.UINT32),
            p(3, 18, "A_ENERGY_THROUGHPUT_KW", SpecType.UINT32),
            p(3, 19, "A_BATTERY_INFORMATION", SpecType.STRING),
            p(3, 20, "A_BATTERY_HEALTH_PER", SpecType.UINT32),
            p(3, 21, "A_SELF_DISCHARGE_RATE_21", SpecType.UINT32),
            p(3, 22, "A_DISCHARGE_CAPACITY", SpecType.UINT32),
            p(3, 23, "A_DISCHARGE_ENERGY", SpecType.UINT16),
            p(3, 24, "A_NUMBER_DISCHARGE_OCC", SpecType.UINT16),
            p(4, 1, "A_FIRST_ACTIVE_TIME", SpecType.UINT32),
            p(4, 2, "A_ACTIVE", SpecType.BOOL),
            p(4, 3, "A_ENERGY_RECOVERY", SpecType.UINT8),
            p(4, 4, "TAIL_LIGHT_IS_ON", SpecType.BOOL),
            p(4, 5, "A_BRAKE_LIGHT_LINKAGE", SpecType.BOOL),
            p(4, 6, "IS_LOCKED", SpecType.BOOL),
            p(4, 7, "A_TCS_TRACTION", SpecType.BOOL),
            p(4, 8, "A_ENVIRONMENTAL_LIGHTS", SpecType.BOOL),
            p(4, 9, "A_BLE_FIND_VEHICLE", SpecType.BOOL),
            p(4, 10, "A_BLE_FIND_SWICH", SpecType.BOOL),
            p(4, 11, "A_E_ABS", SpecType.BOOL),
            p(4, 12, "A_STARTING_SPEED", SpecType.UINT8),
            p(4, 13, "A_AUTO_LOCK", SpecType.BOOL),
            p(4, 14, "A_APPLE_FIND_MY", SpecType.UINT8),
            p(4, 15, "A_AUTOMATIC_SHUTDOWN", SpecType.UINT8),
            p(4, 16, "A_BOOST_MODE", SpecType.BOOL),
            p(4, 18, "A_PHONE_TIME", SpecType.STRING),
            p(4, 21, "A_CHARGING", SpecType.UINT8),
            p(4, 22, "A_FINDMY_BEACON", SpecType.BOOL),
            p(4, 27, "A_TIMER_CHARG_SWITCH", SpecType.BOOL),
            p(4, 29, "A_START_CHARGING_TIMER", SpecType.UINT16),
            p(4, 30, "A_END_CHARGING_TIMER", SpecType.UINT16),
            p(4, 31, "A_BUTTON_LOCK_CAR", SpecType.BOOL),
            p(4, 32, "A_AUTOMATIC_FILLING", SpecType.BOOL),
            p(2, 1, "RIDING_MODE", SpecType.INT8),
            p(2, 2, "A_REMAINING_MILEAGE", SpecType.FLOAT),
            p(2, 3, "A_COMPANION_TIME", SpecType.UINT32),
            p(2, 4, "A_TOTAL_DRIVING", SpecType.FLOAT),
            p(2, 5, "A_MOTOR_TEMPERATURE", SpecType.INT16),
            p(2, 6, "A_DRIVING_TIME", SpecType.UINT32),
            p(2, 7, "A_DRIVING_MILEAGE", SpecType.INT32),
            p(2, 8, "A_AVERAGE_SPEED", SpecType.INT8),
            p(2, 9, "A_RECENT_MILEAGE", SpecType.STRING),
            p(2, 10, "A_DEVICE_INFORMATION", SpecType.STRING),
            p(2, 11, "A_ABNORMAL_REPORTING", SpecType.UINT32),
            p(2, 12, "A_VCU_FIRMWARE_VERSION", SpecType.STRING),
            p(2, 13, "A_VCU_HARDWARE_VERSION", SpecType.STRING),
            p(2, 14, "A_VCU_SN", SpecType.STRING),
            p(2, 15, "A_BMS_FIRMWARE_VERSION", SpecType.STRING),
            p(2, 16, "A_BMS_HARDWARE_VERSION", SpecType.STRING),
            p(2, 17, "A_BMS_SN", SpecType.STRING),
            p(2, 19, "A_SHUTDOWN_STATUS", SpecType.BOOL),
            p(2, 20, "A_VCU_SPEED", SpecType.UINT32),
            p(2, 21, "A_FIND_MY_NAME", SpecType.STRING),
            p(2, 22, "A_VERSION_ALL", SpecType.STRING),
            p(5, 1, "A_MILEAGE_UNIT", SpecType.UINT8),
            p(5, 2, "A_PRESSURE_SWITCH", SpecType.BOOL),
            p(5, 3, "A_PRESSURE_PERIOD", SpecType.UINT8),
            p(5, 4, "A_PRESSURE_START_TIME", SpecType.UINT32),
            p(5, 5, "A_PRESSURE_REST_DAYS", SpecType.UINT8),
        ),
        ride = listOf("A_REMAINING_MILEAGE", "A_COMPANION_TIME", "A_TOTAL_DRIVING", "A_MOTOR_TEMPERATURE", "A_DRIVING_TIME", "A_DRIVING_MILEAGE", "A_AVERAGE_SPEED", "A_RECENT_MILEAGE", "A_ABNORMAL_REPORTING", "A_SHUTDOWN_STATUS", "A_VCU_SPEED"),
        battery = listOf("BATTERY_LEVEL", "A_CHARGING_STATUS", "A_VOLTAGE", "A_ELECTRICITY", "A_BATTERY_HEALTH", "A_BATTERY_TEMP", "A_BATTERY_POWER", "A_BP_RESET_CAPACITY", "A_BP_DIS_CAPACITY", "A_BP_DIS_POWER", "A_BP_CYCLE_TIMES", "A_BP_OVER_DIS_TIMES", "A_BP_CHARGE_SECONDS", "A_BP_STORE_SECONDS", "A_SELF_DISCHARGE_RATE", "A_ENERGY_THROUGHPUT_KW", "A_BATTERY_HEALTH_PER", "A_SELF_DISCHARGE_RATE_21", "A_DISCHARGE_CAPACITY", "A_DISCHARGE_ENERGY", "A_NUMBER_DISCHARGE_OCC"),
        settings = listOf("A_ACTIVE", "A_ENERGY_RECOVERY", "TAIL_LIGHT_IS_ON", "A_BRAKE_LIGHT_LINKAGE", "IS_LOCKED", "A_TCS_TRACTION", "A_ENVIRONMENTAL_LIGHTS", "A_BLE_FIND_VEHICLE", "A_BLE_FIND_SWICH", "A_E_ABS", "A_STARTING_SPEED", "A_AUTO_LOCK", "A_APPLE_FIND_MY", "A_AUTOMATIC_SHUTDOWN", "A_BOOST_MODE", "A_PHONE_TIME", "A_CHARGING", "A_FINDMY_BEACON", "A_TIMER_CHARG_SWITCH", "A_START_CHARGING_TIMER", "A_END_CHARGING_TIMER", "A_BUTTON_LOCK_CAR", "A_AUTOMATIC_FILLING", "RIDING_MODE"),
        vehicle = listOf("A_MILEAGE_UNIT", "A_PRESSURE_SWITCH", "A_PRESSURE_PERIOD", "A_PRESSURE_START_TIME", "A_PRESSURE_REST_DAYS"),
        ident = listOf("A_BATTERY_SN", "A_BATTERY_DATE", "A_BATTERY_INFORMATION", "A_FIRST_ACTIVE_TIME", "A_DEVICE_INFORMATION", "A_VCU_FIRMWARE_VERSION", "A_VCU_HARDWARE_VERSION", "A_VCU_SN", "A_BMS_FIRMWARE_VERSION", "A_BMS_HARDWARE_VERSION", "A_BMS_SN", "A_FIND_MY_NAME", "A_VERSION_ALL"),
    )

    val BY_MODEL: Map<String, SpecProfile> = mapOf(
        "xiaomi.scooter.elite" to ELITE,
        "xiaomi.scooter.5plus" to PLUS_5,
        "xiaomi.scooter.6" to SIX,
        "xiaomi.scooter.6lite" to SIX_LITE,
        "xiaomi.scooter.6esstl" to SIX_ESSTL,
        "xiaomi.scooter.6pro" to SIX_PRO,
        "xiaomi.scooter.cross" to SIX_ULTRA,
    )
}
